from io import BytesIO

import streamlit as st
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate


def show_report(row, country, year, recommendation):
    """
    Display the Sustainability Report page and generate a PDF report.
    """

    # =====================================
    # Climate Impact Calculations
    # =====================================

    co2 = row["Total_GW"] * 1200
    trees = int(co2 / 21)
    homes = int(row["Total_GW"] * 500000)
    cars = int(co2 / 4600)

    # =====================================
    # Report Page
    # =====================================

    st.title("📄 Sustainability Report")

    st.markdown(f"""
## 🌿 Renewable Energy Summary

**Country:** {country}

**Year:** {year}

### ⚡ Key Statistics

- **Total Renewable Capacity:** {row['Total_GW']:.1f} GW
- **Population:** {row['Population_M']:.0f} Million
- **GDP:** ${row['GDP_Billion_USD']:.0f} Billion

### ☀ Renewable Energy Breakdown

- ☀️ Solar: {row['Solar_GW']:.1f} GW
- 💨 Wind: {row['Wind_GW']:.1f} GW
- 💧 Hydro: {row['Hydro_GW']:.1f} GW
- 🌿 Biomass: {row['Biomass_GW']:.1f} GW
- 🌋 Geothermal: {row['Geothermal_GW']:.1f} GW

### 🌍 Environmental Benefits

- CO₂ Saved: **{co2:,.0f} Tons**
- Equivalent Trees: **{trees:,}**
- Homes Powered: **{homes:,}**
- Cars Removed: **{cars:,}**

### 🤖 AI Recommendation

> {recommendation}

---

**Generated by Renewable Energy Awareness Chatbot**

*Built for the 1M1B Green Internship*
""")

    # =====================================
    # PDF Generation
    # =====================================

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph(
            "Renewable Energy Sustainability Report",
            styles["Title"],
        )
    )

    story.append(Paragraph(f"<b>Country:</b> {country}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Year:</b> {year}", styles["BodyText"]))

    story.append(
        Paragraph(
            f"<b>Total Renewable Capacity:</b> {row['Total_GW']:.1f} GW",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            f"<b>Population:</b> {row['Population_M']:.0f} Million",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            f"<b>GDP:</b> ${row['GDP_Billion_USD']:.0f} Billion",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            "<b>Renewable Energy Sources</b>",
            styles["Heading2"],
        )
    )

    story.append(Paragraph(f"Solar: {row['Solar_GW']:.1f} GW", styles["BodyText"]))
    story.append(Paragraph(f"Wind: {row['Wind_GW']:.1f} GW", styles["BodyText"]))
    story.append(Paragraph(f"Hydro: {row['Hydro_GW']:.1f} GW", styles["BodyText"]))
    story.append(Paragraph(f"Biomass: {row['Biomass_GW']:.1f} GW", styles["BodyText"]))
    story.append(Paragraph(f"Geothermal: {row['Geothermal_GW']:.1f} GW", styles["BodyText"]))

    story.append(
        Paragraph(
            "<b>Climate Impact</b>",
            styles["Heading2"],
        )
    )

    story.append(Paragraph(f"CO₂ Saved: {co2:,.0f} Tons", styles["BodyText"]))
    story.append(Paragraph(f"Equivalent Trees: {trees:,}", styles["BodyText"]))
    story.append(Paragraph(f"Homes Powered: {homes:,}", styles["BodyText"]))
    story.append(Paragraph(f"Cars Removed: {cars:,}", styles["BodyText"]))

    story.append(
        Paragraph(
            "<b>AI Recommendation</b>",
            styles["Heading2"],
        )
    )

    story.append(
        Paragraph(
            recommendation,
            styles["BodyText"],
        )
    )

    doc.build(story)

    # =====================================
    # Download Button
    # =====================================

    st.download_button(
        "📄 Download PDF Report",
        buffer.getvalue(),
        file_name=f"{country}_{year}_Renewable_Report.pdf",
        mime="application/pdf",
        use_container_width=True,
    )
